name: jvm-binary
version: '0.1.0'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: MIT
license-file: LICENSE.md
category: Language, Java, JVM
github: ucla-pls/jvm-binary

description: A library for reading Java class-files.


extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

dependencies:
- base >= 4.9 && < 4.11
- binary
- bytestring
- containers
- text
- vector
- deepseq >= 1.4.3.0
- deriving-compat
- attoparsec 

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  jvm-binary-test:
    dependencies:
    - jvm-binary
    - tasty
    - tasty-hspec
    - tasty-discover
    - tasty-quickcheck
    - filepath
    - directory
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fno-warn-orphans
    main: Test.hs
    source-dirs: test

benchmarks:
  jvm-binary-benchmarks:
    dependencies:
    - jvm-binary
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -funbox-strict-fields
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
