name: jvm-binary
version: '0.1.0'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: MIT
license-file: LICENSE.md
category: Language, Java, JVM
github: ucla-pls/jvm-binary

description: A library for reading Java class-files.

ghc-options: -Wall

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

library:
  dependencies:
  - base >= 4.10 && < 4.11
  - binary
  - bytestring
  - containers
  - text
  - vector
  - deepseq
  - deriving-compat
  - megaparsec >= 6.2.0
  source-dirs: src

tests:
  jvm-binary-test-suite:
    dependencies:
    - base >= 4.10 && < 4.11
    - jvm-binary
    - tasty
    - tasty-hspec
    - tasty-discover
    - tasty-quickcheck
    - binary
    - bytestring
    - containers
    - filepath
    - deriving-compat
    - directory
    - text
    - megaparsec >= 6.0.0
    - hspec-megaparsec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fno-warn-orphans
    main: Test.hs
    source-dirs: test-suite

benchmarks:
  jvm-binary-benchmarks:
    dependencies:
    - base >= 4.10 && < 4.11
    - jvm-binary
    - criterion
    - bytestring
    - deriving-compat
    ghc-options:
    - -rtsopts
    - -threaded
    - -funbox-strict-fields
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
